# Programming Assignment 6

**Author:** Molly Rovinski
**Version:** 1.0
**Semester:** Fall 2020

**Problem A:** Create a 2-by-2 NumPy array with elements 10,20,30, and 40 in it.

In [1]:
import numpy as np
a = np.array([[10,20],[30,40]])
print (a**2)

[[ 100  400]
 [ 900 1600]]


In [16]:
b = 100
print (a + b)

[[110 120]
 [130 140]]


In [17]:
c = 5
print (a*c)

[[ 50 100]
 [150 200]]


In [3]:
print (a**(1/2))

[[3.16227766 4.47213595]
 [5.47722558 6.32455532]]


**Problem B:** Create a 3-by-3 array containing integers from 3 to 27 in multiples of 3. Create a 3-by-3 array with 9 elements evenly spaced between 10 and 20. Multiply them together.

In [11]:
x = np.arange (3,28)
n = x[(x % 3 ==0)]
d = np.array (n). reshape((3,3))
print (d)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [12]:
y = np.arange (11,20)
f = np.array(y). reshape((3,3))
print (f)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [13]:
print ((d * f))

[[ 33  72 117]
 [168 225 288]
 [357 432 513]]


**Problem C:** Create a 5-by-5 NumPy Array from the five attached .npy files. Calculate the mean of each column of data. 

In [73]:
d1 = np.load('process1.npy')

In [75]:
d2 = np.load('process2.npy')

In [76]:
d3 = np.load('process3.npy')

In [77]:
d4 = np.load('process4.npy')

In [78]:
d5 = np.load('process5.npy')

In [80]:
print (d1)
print (d2)
print (d3)
print (d4)
print (d5)

[[52 12 81  0 58]]
[[96  4 61 16 43]]
[[38 96 45 17 58]]
[[97 21 22 25  6]]
[[77  6 19  2 74]]


In [92]:
data1 = np.stack([d1,d2,d3,d4,d5])
print (data1)

[[[52 12 81  0 58]]

 [[96  4 61 16 43]]

 [[38 96 45 17 58]]

 [[97 21 22 25  6]]

 [[77  6 19  2 74]]]


In [100]:
print(np.mean(data1, axis=0))

[[72.  27.8 45.6 12.  47.8]]
